# Generated by Django 5.1.7 on 2025-04-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_donor_email_transaction_donor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='convert_to',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
