# Generated by Django 5.1.7 on 2025-04-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_campaign_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='convert_to',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
