# Generated by Django 5.1.7 on 2025-04-25 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_campaign_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('telebirr', 'Telebirr')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='convert_to',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('birr', 'Birr')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('telebirr', 'Telebirr')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
