# Generated by Django 5.1.7 on 2025-05-01 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_campaign_target_amount_campaign_target_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='completed',
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ETB', 'ETB')], default='usd', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ETB', 'ETB')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.campaign'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('telebirr', 'Telebirr')], max_length=50),
        ),
    ]
