# Generated by Django 4.2.21 on 2025-05-24 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0011_remove_transaction_currency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="target_amount",
            new_name="goal",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="target_currency",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
