# Generated by Django 4.2.21 on 2025-05-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_rename_target_amount_campaign_goal_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="withdrawalrequest",
            old_name="amount_birr",
            new_name="requested_amount",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="amount_usd",
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="convert_to",
            field=models.CharField(
                choices=[("usd", "USD"), ("birr", "Birr")],
                default="birr",
                max_length=10,
            ),
        ),
    ]
