# Generated by Django 5.2.1 on 2025-05-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0013_rename_amount_birr_withdrawalrequest_requested_amount_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="donor_phone",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="recipient_phone",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[("paypal", "PayPal"), ("chapa", "Chapa")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="payment_method",
            field=models.CharField(
                choices=[("paypal", "PayPal"), ("chapa", "Chapa")], max_length=20
            ),
        ),
    ]
